### ISSUE TITLE
Document platforms' order states

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/standard#16]
Map order states used by platform and how they should implement them in the standard

Use gitbook to document it for now, but we need to come up with a better solution?

We can use this work to start improving the implementation documentation

**Comment by RaggedStaff** [comment]
Here is the [initial mapping work](https://docs.google.com/spreadsheets/d/1jP6Wc5cx6uuuJZR6vGKffNzuypGNxBHFYodO74GGWak/edit#gid=0) I did last year.

**Comment by simonLouvet** [comment]
ok to document that on gitbook as annex attached to ontology main page
