### ISSUE TITLE
Find an alternative to framgroups/SYMPA to manage the release email list

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/standard#23]
## Context

- Mobile UX is confusing
- The double confirm UX is leading people to not confirm their subscription

See : https://datafoodconsortium.slack.com/archives/C3CKZMWC9/p1713885621462159

## Acceptance criteria

- Find an email register that we can use preferably for free
- And preferably FOSS 

## Tasks

- [x] @RachL to setup an account with the DFC email
- [ ] @RaggedStaff to set up & share release mailing list

**Comment by RaggedStaff** [comment]
So the 2 top Free (as in speech) mailing software app's that I've heard of are: Listmonk & PHPlist.

PHPlist have a SaaS offering, [which might be free, or $1/month,](https://www.phplist.com/pricing) I'm a bit confused 😕 or we could self-host.

[Listmonk,](https://listmonk.app/) we'd have to self-host, I can't find any SaaS offering, although they do offer docker & some PaaS solutions we could utilise.

**Comment by RaggedStaff** [comment]
Ping @RachL - the PHPList Free for Open Source programme would be great for DFC - we could have a general mailing list too! Would need someone from DFC (with a DFC email) to apply though I think. 

What do you think? Could you bring to the FR meeting (is that tomorrow? :confused: )  ?

**Comment by RachL** [comment]
Yes will do :+1:
